openapi: 3.0.0
info:
  title: Ping API
  description: API de test
  version: 1.0.0
paths:
  /ping:
    get:
      responses:
        200:
          description: retour Pong
          content:
            text/plain:
              schema:
                type: string
                example: pong