openapi: 3.0.0
info:
  title: Product Search API
  version: 1.0.0
  description: API pour la recherche de produits
paths:
  /products:
    get:
      summary: Recherche des produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste des produits trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Plusieurs produits trouvés
                  value:
                    - name: "Laptop"
                      expiration_datetime: "2024-12-31T23:59:59Z"
                      price: 999.99
                    - name: "Smartphone"
                      expiration_datetime: "2024-10-15T12:00:00Z"
                      price: 499.99
                emptyList:
                  summary: Aucun produit trouvé
                  value: []

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
      required:
        - name
        - expiration_datetime
        - price

  parameters:
    limit:
      name: limit
      in: query
      description: Nombre maximum d'éléments à retourner
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    q:
      name: q
      in: query
      description: Terme de recherche
      required: false
      schema:
        type: string