openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: API complète avec gestion de produits et commandes
paths:
  /products:
    get:
      tags:
        - Products
      summary: Recherche des produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste des produits trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /orders:
    get:
      tags:
        - Orders
      summary: Liste paginée des commandes
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Liste des commandes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
              examples:
                ordersExample:
                  summary: Exemple de commandes
                  value:
                    - identifier: 1
                      customer_name: "Alice Dupont"
                      creation_datetime: "2024-08-21T10:30:00Z"
                      total_amount: 1499.98
                    - identifier: 2
                      customer_name: "Bob Martin"
                      creation_datetime: "2024-08-21T14:45:00Z"
                      total_amount: 299.99

    post:
      tags:
        - Orders
      summary: Créer une nouvelle commande
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              newOrder:
                summary: Exemple de nouvelle commande
                value:
                  customer_name: "Jean Dupont"
                  total_amount: 199.99
      responses:
        '201':
          description: Commande créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float

    Order:
      type: object
      properties:
        identifier:
          type: integer
          readOnly: true
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
          readOnly: true
        total_amount:
          type: number
          format: float
      required:
        - customer_name
        - total_amount

  parameters:
    limit:
      name: limit
      in: query
      description: Nombre maximum d'éléments à retourner
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    q:
      name: q
      in: query
      description: Terme de recherche
      required: false
      schema:
        type: string
    page:
      name: page
      in: query
      description: Numéro de page
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    size:
      name: size
      in: query
      description: Taille de la page
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic